services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql-db
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  mysql-volume: