services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: